# https://pr-agent-docs.codium.ai/
# https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml

[config]
ignore_pr_labels = ['renovate']
ai_timeout = 600

[ignore]
glob = ['*.lock.hcl','*.toml']

[pr_description]
generate_ai_title = true
final_update_message = true
extra_instructions="""\
下記のルールに従ってください
- 日本語を使用してください。
- タイトルは、feat:, chore:, test:, fix:, docs:, style:, refactor:, perf: などのように、commitlintのパターンに従ってください。
- 最後にpr-agentで実行できるコマンドを箇条書きで羅列してください
"""

[pr_reviewer]
require_tests_review = false
require_can_be_split_review	= true
num_code_suggestions = 3
inline_code_comments = true
enable_auto_approval = true
maximal_review_effort = 3
extra_instructions="""\
日本語を使用してください。
あなたは AWS や GCP や Azureなどのクラウドサービス、terraform などの Infrastructure as Code に精通したプログラマーです。
渡されたコードについて改善点を見つけ、変更する理由を説明した上で、変更後のコード例を示してください。
あなたが提案するコード（Suggestion Change）には、適切にインデントを含めるようにしてください。
[コード規約] に従ってください。
改善点がない場合には絶対にコメントをしないでください。

特に以下の点を指摘してください:
  - 誤解を招いたり、実態を正確に表していない命名があるか
  - 冗長な書き方のコードがないか
  - 読んで理解が難しい箇所にコメントが適切にされているか
  - コメントの内容は日本語として読んでわかりやすく、簡潔に説明できているか
  - 理解の難しい複雑な条件式が作られていないか
  - 明らかなセキュリティの問題があるか
  - terraform で モジュールや ステイトは適切に分割されているか
"""

[pr_code_suggestions]
summarize = false
max_context_tokens = 128000
num_code_suggestions = 7
rank_suggestions = true
commitable_code_suggestions = true
demand_code_suggestions_self_review = true
extra_instructions="""\
下記のルールに従ってください
- 日本語を使用してください。
"""
