name: Code Review

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
  issue_comment:
    types:
      - created
      - edited

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Run pr agent on every pull request
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - name: PR Agent action step
        id: prAgent
        uses: Codium-ai/pr-agent@v0.25
        env:
          OPENAI_KEY: ${{ secrets.AZURE_CODE_REVIEW_OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_TYPE: 'azure'
          OPENAI.API_VERSION: '2024-10-01'
          OPENAI.API_BASE: ${{ vars.AZURE_CODE_REVIEW_API_BASE }}
          OPENAI.DEPLOYMENT_ID: gpt-4
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: false
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
